-- Add missing character fields for AI-generated personas
-- These fields are generated by the CharacterGeneratorAgent

ALTER TABLE brand_characters
ADD COLUMN IF NOT EXISTS backstory TEXT,
ADD COLUMN IF NOT EXISTS voice TEXT,
ADD COLUMN IF NOT EXISTS archetype VARCHAR(100),
ADD COLUMN IF NOT EXISTS day_of_week VARCHAR(20),
ADD COLUMN IF NOT EXISTS emotional_range JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS speaking_style TEXT,
ADD COLUMN IF NOT EXISTS quirks JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS relationships TEXT,
ADD COLUMN IF NOT EXISTS growth_arc TEXT,
ADD COLUMN IF NOT EXISTS content_strengths JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS sample_quotes JSONB DEFAULT '[]'::jsonb;

-- Add constraint for day_of_week
ALTER TABLE brand_characters
DROP CONSTRAINT IF EXISTS check_day_of_week;

ALTER TABLE brand_characters
ADD CONSTRAINT check_day_of_week CHECK (
  day_of_week IS NULL OR
  day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')
);

-- Create index for day_of_week for querying characters by day
CREATE INDEX IF NOT EXISTS idx_brand_characters_day ON brand_characters(day_of_week);

-- Comment on new columns
COMMENT ON COLUMN brand_characters.backstory IS 'Character backstory generated by AI';
COMMENT ON COLUMN brand_characters.voice IS 'Character voice/speaking style description';
COMMENT ON COLUMN brand_characters.archetype IS 'Character archetype (e.g., The Hero, The Sage)';
COMMENT ON COLUMN brand_characters.day_of_week IS 'Assigned day of week for character content';
COMMENT ON COLUMN brand_characters.emotional_range IS 'Array of emotions this character can express';
COMMENT ON COLUMN brand_characters.speaking_style IS 'How the character speaks/writes';
COMMENT ON COLUMN brand_characters.quirks IS 'Array of unique character quirks';
COMMENT ON COLUMN brand_characters.relationships IS 'Relationships with other characters';
COMMENT ON COLUMN brand_characters.growth_arc IS 'Character development arc';
COMMENT ON COLUMN brand_characters.content_strengths IS 'Array of content types this character excels at';
COMMENT ON COLUMN brand_characters.sample_quotes IS 'Array of sample quotes from this character';
